.ORG 0X0000
    
    LDI R16, 0B11111111
    OUT DDRD, R16	;CONFIGURAR O PORTD COMO SAÍDA
    
    LDI R16, 0B00000000
    OUT DDRC, R16	;CONFIGURA O PORTC COMO ENTRADA

    LDI R16, 0B00001100
    OUT	PORTC, R16	;ATIVA OS RESISTORES DE PULL-UPS INTERNOS
    

    
LOOP:
    SBIC    PINC, PC2
    SBIC    PIND, PD7
    RJMP    APAGA_LED
    RJMP    ACENDE_LED
    
APAGA_LED:
    CBI PORTD, 7    ;APAGA O LED DO PD7
    RJMP LOOP

ACENDE_LED:
    SBI PORTD, 7    ;ACENDE O LED DO PD7
    RJMP LOOP
    


