.ORG 0X0000
    
    LDI R16, 0B11111111
    OUT DDRD, R16
    
    LDI	R16, 0
    OUT PORTD, R16
    
    
    LDI R20, 230    ;255
    LDI R21, 230
    CPSE R20, R21   ;COMANDO QUE COMPARA OS DOIS REGISTRADORES E PULA UMA LINHA SE FOREM IGUAIS
    RJMP    DIFERENTE	;SE FOREM DIFERENTES PULA PRA FLAG DIFERENTE
    RJMP    IGUAL

    
LOOP:
    RJMP LOOP
    
DIFERENTE:
    CBI PORTD, 7    ;APAGA O LED DO PB7
    RJMP LOOP

IGUAL:
    SBI PORTD, 7    ;ACENDE O LED DO PB7
    RJMP LOOP
    

