.ORG	0x0000   ;Avisa ao microcontrolador qual que é o primeiro endereço de memória que será gravado
    
;Um uC do tipo CISC
;    MOV REG. DESTINO, VALOR DE ORIGEM

;RISC
   ;LOAG REG. DESTINO, VALOR
   ;STORE REG. ESPECIAL, REG. GERAL

;ACENDER O LED13 NO PORTB
   ;          7       0
   LDI	R16, 0B11111111	    ;REGISTRADOR DE USO GERAL
   OUT	DDRB, R16	    ;REGISTRADOR DE USO ESPECIAL
			    ;RECEBE O PARÂMETRO DO REGISTRADOR DE USO GERAL
			    ;DEFININDO TODO O PORTB COMO SAÍDA
    
    LDI R17, 0B10000000
    OUT PORTB, R17	    ;DETERMINA O PB7 COMO SAÍDA PARA ACENDER O LED
    
    
LOOP:			    ;AO USAR DOIS PONTOS ISSO VIRA UM LABEL
			    ;LABEL É UMA ETIQUETA COM ENDEREÇO FÍSICO NA MEMÓRIA
    RJMP    LOOP
			    
